FROM node:14-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm", "run", "start" ]


#docker build -t backend-devops:v3 .
#docker run -p 3000:3000 backend-devops:v3