pipeline {
  environment {
    registry = "fcambres/webdemo"
    registryCredential = 'dockerhub_id'
    dockerImage = ''
  }
  
  agent any
  stages {

    //Empieza Test
    stage('Test') {
      steps {
         script {
          dir('cicd/app-devops-bootcamp/api-store') {
            sh 'npm install'
            sh 'npm run test'
          }
        }
      }
    }
       
    //Finaliza test
    
    //Inicia Stage Build
    stage('build Image') {
      steps {
        echo 'Haciendo el Build de la app'
        script {
          dir('cicd/app-devops-bootcamp/api-store') {
            docker.build registry + ":v1.$BUILD_NUMBER"
          }
        } 
      }
    }
    //Finaliza Stage Build
    //Inicia Stage change tag
    stage('Change tag to deployment.yaml') {
      steps {
        echo 'Cambiando el tag de la imagen en el deployment.yaml'
        withCredentials([gitUsernamePassword(credentialsId: 'my-git-user', gitToolName: 'git-tool')]) {
        script {
          dir('manifiestos-eks/dev') {
            sh '''
              git config --global user.email "jiolloker@example.com"
              git config --global user.name "jiolloker"
              ssed -i \"s/fcambres\\/webdemo:v[0-9]\\+\\.[0-9]\\+/fcambres\\/webdemo:$BUILD_NUMBER/g\" deployment.yml
              git add deployment.yml
              git commit -m \"Update image tag to $BUILD_NUMBER\"
              git push origin master
            '''
            } 
          }
        }
      }
    }

    
    //Inicia Stage Push
    stage('Push Image') {
      steps {
        echo 'Haciendo un Push a la registry de docker'
        script {
          docker.withRegistry('https://registry.hub.docker.com/', 'dockerhub_id') {
          docker.image("fcambres/webdemo:v1.$BUILD_NUMBER").push()
          }
        }
      }
    }
    //Finaliza Stage Push
    //Empieza Limpieza
    stage('Cleaning Image') {
      steps{
      sh "docker rmi $registry:v1.$BUILD_NUMBER"
      sh "docker rmi registry.hub.docker.com/$registry:v1.$BUILD_NUMBER"
      }
    }
    //Finaliza Limpieza
  }
}

